# config for training and evaluation
data_dir: "data"
train_dir: "data/train"
val_dir: "data/val"
test_dir: "data/test"


batch_size: 1
epochs: 2
lr: 0.0001
save_dir: "checkpoints"
output_dir: "outputs"
device: "cpu" # or "cuda"


patch_size: [64, 128, 128] # (D, H, W) â€” adjust according to memory
num_workers: 4


# model
in_channels: 1
out_channels: 1
base_filters: 16


# misc
seed: 42